### ISSUE TITLE
What is this repository for?

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/go-key#1]
I am curious.

**Comment by geoah** [comment]
@whyrusleeping made this repo so the `go-ipfs` package [`blocks/key`](https://github.com/ipfs/go-ipfs/tree/master/blocks/key) could be split from `go-ipfs` as it was needed by [libp2p/go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht) (and probably other packages).

:)
